/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes1;
import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

public class App {


    public static void main(String[] args) throws FileNotFoundException {
getRandomBook();
    }

    public static String getRandomBook() throws FileNotFoundException {
        Gson gson = new Gson();
        Reader reader = new FileReader("/home/sabbagh99/Desktop/ASAC/code-401/quotes1/app/src/main/resources/recentquotes.json");
        recentQuotes[] convertedObject = gson.fromJson(reader, recentQuotes[].class);
        int rand = (int) Math.floor(Math.random() * (158 - 0 + 1) + 0);
        String bookName = "";
        bookName += convertedObject[rand];
        System.out.println(bookName);
        return bookName;
    }
    public static String getSpecificBook(int num, Reader file) throws FileNotFoundException {
        Gson gson = new Gson();
        recentQuotes[] convertedObject = gson.fromJson(file, recentQuotes[].class);
        String bookName = "";
        bookName += convertedObject[num];
        System.out.println(bookName);
        return bookName;
    }

}