/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes1;

import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testGetRandomBook() throws FileNotFoundException {
        App classUnderTest = new App();
        assertEquals("java.lang.String", classUnderTest.getRandomBook().getClass().getName());
        assertTrue("recentQuotes{\n" +
                "tags=null\n" +
                ", author='Ron Swanson'\n" +
                ", likes='null'\n" +
                ", text='\"One rage every three months is permitted. Try not to hurt anyone who doesn't deserve it.\"'}\n", classUnderTest.getRandomBook().contains("author"));
    }

    @Test
    public void testGetSpecificBook() throws  FileNotFoundException {
        Reader reader = new FileReader("src/main/resources/recentquotes.json");

        App classUnderTest = new App();
        assertEquals("recentQuotes{\n" +
                "tags=[monsters]\n" +
                ", author='Chuck Klosterman'\n" +
                ", likes='0 likes'\n" +
                ", text=' “It's easier to believe there's a monster under the bed if you've spent the last six months arguing with a monster.” '}", classUnderTest.getSpecificBook(10,reader));
    }
}
